### ISSUE TITLE
Propozycja zmiany odnośnie obliczeń

### ISSUE THREAD

**Issue by PiotrOrzeszek** [JoannaSitarek/ZabawyPythonem#1]
https://github.com/JoannaSitarek/ZabawyPythonem/blob/cbd83186239538c2b3552ff70cec617befd4d8ed/pierwszaZabawaPythonem.py#L6

Ależ Joanno, czyż nie powinno być w tym miejscu `print(2+2)`?

**Comment by JoannaSitarek** [comment]
Ależ Piotr, to jest w pełni w porządku.
Nie masz racji ;-)
